name: Check Format

on: pull_request

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: 1.14.4
          otp-version: 25.0

      - name: Install dependencies
        run: mix deps.get

      - name: Check format
        run: mix format --check-formatted
