name: Credo

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1.10
        with:
          otp-version: 25.0
          elixir-version: 1.14.4
      - name: Get Deps Cache
        uses: actions/cache@v3
        id: deps
        with:
          path: deps/
          key: ${{hashFiles('mix.lock')}}-deps

      - name: Get Build Cache
        uses: actions/cache@v2
        with:
          path: _build/
          key: ${{runner.os}}-${{hashFiles('mix.lock')}}-build

      - name: Get deps
        if: steps.deps.outputs.cache-hit == 'false'
        run: |
          mix deps.get

      - name: Check Credo
        run: |
          mix credo --strict