name: Dialyzer CI

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get Deps Cache
      uses: actions/cache@v3
      id: deps
      with:
        path: deps/
        key: ${{hashFiles('mix.lock')}}-deps

    - name: Get Build Cache
      uses: actions/cache@v2
      with:
        path: _build/
        key: ${{runner.os}}-${{hashFiles('mix.lock')}}-build

    - name: Setup elixir
      uses: erlef/setup-beam@v2
      with:
        otp-version: 25.0
        elixir-version: 1.14.4

    - name: Get deps
      if: steps.deps.outputs.cache-hit != 'true'
      run: |
        mix deps.get

    - name: Run Dialyzer
      run: mix dialyzer